/**
 * ★★★**표현 사전 — 원자는 그대로, «보이는 말»만 사람 말로** (대표 2026-09-18 「텍스트 좀 잘 해보고」)
 *   ⚠ 화면에 원자의 영문 키가 그대로 섰다 — 정책 `additional_driver_allowance_count` · 차종 매칭 `UNMATCHED`.
 *   ⇒ 이름표는 새로 짓지 않고 **옛 ERP 정본**에서 옮겼다: freepasserp4 `lib/intake/entities.ts` 의 { key, label }
 *     (시트 규격 글자 그대로 — 영업·공급사가 쓰는 말). 거기 고치면 여기도 같이 고친다.
 *   ⓘ 사전에 없는 키는 영문 그대로 두지 않고 「밑줄 → 띄어쓰기」로만 풀어 보인다 — 없는 말을 지어내지 않는다.
 */
export const 정책이름: Record<string, string> = {
  accident_history: "사고여부",
  accident_termination_count: "사고 다발 해지기준",
  action: "동작",
  actor_name: "행위자",
  actor_role: "역할",
  adapter_id: "시트 어댑터",
  additional_driver_allowance_count: "추가운전 인원",
  additional_driver_cost: "추가운전 요금(1인당 월)",
  address: "주소",
  admin_settlement: "월정산서",
  admin_settlement_code: "정산서코드",
  age_lowering_cost: "연령 하향 요금(월)",
  age_surcharge_snapshot: "연령 가산(월)",
  agency_incentive: "에이전시 인센티브",
  agency_pay: "지급액",
  agent_balance_paid: "계약금입금",
  agent_channel_code: "영업채널코드",
  agent_code: "영업자코드",
  agent_delivery_inquiry: "출고문의",
  agent_docs_submitted: "서류제출",
  agent_final_paid: "잔금입금",
  agent_handover_confirmed: "인도확인",
  agent_name: "영업자명",
  agent_payout: "영업자지급(원)",
  agent_payout_rate: "영업자 지급율(0~1)",
  agent_uid: "영업자UID",
  alias: "별칭",
  annual_mileage: "약정 주행거리",
  annual_mileage_snapshot: "약정주행거리",
  annual_roadside_assistance: "[계약회사별] 긴급출동",
  at: "제보시각",
  audit_log: "감사로그",
  auto_terminate_overdue_days: "차량회수 기준일",
  bank_account: "입금계좌번호",
  bank_holder: "예금주",
  bank_name: "입금은행",
  basic_driver_age: "기본운전자연령",
  batch_id: "첨부묶음",
  battery_capacity: "배터리용량(kWh)",
  birth: "생년월일(YYMMDD)",
  biz_category: "업태 · 종목",
  business_driver_scope: "사업자 운전범위",
  business_name: "상호",
  business_no: "사업자등록번호",
  business_number: "사업자등록번호",
  buyout_notice_days: "인수 사전통지기한(일)",
  cancelled_at: "취소시각",
  car_number: "차량번호",
  car_number_snapshot: "차량번호",
  catalog_id: "차종 카탈로그 id",
  ceo: "대표자",
  cert_car_name: "등록증 차명",
  channel: "채널",
  claim_basis: "청구 기준",
  clawback_amount: "환수액(원)",
  commission_clawback_condition: "수수료 환수조건",
  company_code: "소속코드",
  company_name: "소속명",
  contact: "담당/연락처",
  contact_email: "담당자 이메일",
  contact_name: "담당자 이름",
  contact_phone: "담당자 연락처",
  contract: "계약",
  contract_authoring: "계약서 작성",
  contract_code: "계약코드",
  contract_date: "계약일",
  contract_draft: "계약서 초안 JSON",
  contract_source: "전자계약 생성경로",
  contract_status: "계약상태",
  contracts_per_customer_limit: "1인당 계약 대수",
  corporate_registration_no: "법인등록번호",
  created_at: "발신시각",
  credit_display: "심사표기",
  credit_grade: "신용등급",
  credit_grade_snapshot: "심사기준",
  customer: "고객",
  customer_address: "주소",
  customer_birth: "생년월일(YYMMDD)",
  customer_business_number: "사업자등록번호",
  customer_company_name: "법인/상호",
  customer_email: "이메일",
  customer_id: "주민등록번호",
  customer_is_business: "사업자",
  customer_name: "계약자명",
  customer_phone: "연락처",
  customer_uid: "고객UID",
  delivery_fee: "탁송비",
  delivery_region: "인도지역",
  deposit_amount: "보증금(원)",
  deposit_amount_snapshot: "보증금(원)",
  deposit_card_payment: "보증카드",
  deposit_free: "무보증 가능",
  deposit_installment: "보증금 분납",
  deposit_overdue_rounds: "보증금 미납 시동제어(회차)",
  deposit_return_days: "보증금 반환기한",
  deposit_rule: "보증금 계산규칙",
  designated_garage: "지정 정비점",
  disqualification_conditions: "불가조건",
  doc_agency_fee: "대행료",
  doc_images: "서류사진",
  doc_license: "운전면허증",
  drive_type: "구동",
  driver_age: "가능연령",
  driver_age_lowering: "연령하향",
  driver_age_upper_limit: "최대연령",
  driver_license_no: "면허번호",
  early_termination_rate_over1y: "중도해지 위약금 · 1년 이상",
  early_termination_rate_under1y: "중도해지 위약금 · 1년 미만",
  emergency_name: "비상연락 성명",
  emergency_phone: "비상연락처",
  emergency_relation: "비상연락 관계",
  engine_cc: "배기량(cc)",
  engine_control_overdue_days: "시동제어 기준일",
  engine_type: "원동기형식",
  entity: "대상엔티티",
  esign_contract_enabled: "프리패스 전자계약",
  esign_document_sha256: "PDF SHA-256",
  esign_id: "외부 서명ID",
  esign_import_adapter_id: "엑셀 Adapter ID",
  esign_import_template_id: "엑셀 입력양식 ID",
  esign_provider: "전자계약 제공자",
  esign_required_documents: "고객 추가 제출서류",
  esign_revision: "전자계약 회차",
  esign_seal_hash: "문서 봉인 해시",
  esign_session_hash: "프리패스 서명 세션 해시",
  esign_sign_url: "손님 서명 링크",
  esign_submitted_at: "고객 제출시각",
  esign_verify_url: "검증 링크",
  event_tags: "이벤트 뱃지",
  ext_color: "외부색상",
  fee_amount: "공급사수수료(원)",
  fee_rate: "공급사 수수료율(0~1)",
  fee_rate_snapshot: "공급사수수료율(동결)",
  fee_rate_unresolved: "요율 미확정",
  file_name: "파일명",
  file_url: "파일",
  first_registration_date: "최초등록일",
  fp_options: "표준옵션 ID",
  fuel_type: "연료",
  fuel_type_snapshot: "연료",
  gps_installed: "GPS 장착",
  header_row: "헤더 행(0부터)",
  image_url: "이미지",
  image_urls: "상품사진",
  impound_fee: "물품 보관료(일)",
  impound_keep_days: "물품 보관기간(일)",
  injury_compensation_limit: "[계약회사별] 대인 보상한도",
  injury_deductible: "[계약회사별] 대인 면책금",
  insurance_included: "보험 포함",
  insurance_summary: "보험요약",
  insurer_name: "가입 보험사·공제조합",
  int_color: "내부색상",
  interior_photo: "실내사진 URL",
  is_active: "활성",
  is_admin_chat: "관리자 소통방",
  is_business: "사업자",
  is_draft: "초안",
  is_team_manager: "팀매니저",
  last_message: "마지막메시지",
  last_message_at: "마지막시각",
  last_read_at_admin: "관리자 열람시각",
  last_read_at_agent: "영업자 열람시각",
  last_read_at_provider: "공급사 열람시각",
  last_sender_code: "마지막발신 코드",
  last_sender_role: "마지막발신 역할",
  last_sheet_imported: "최근 유입 대수",
  last_sheet_rows: "최근 시트 행수",
  last_synced_at: "최근 동기화",
  late_fee_rate: "지연손해금율(0~1)",
  license_no: "면허번호",
  license_period: "면허 경력요건",
  linked_contract: "연결 계약코드",
  location: "위치",
  maintenance_service: "정비",
  maker: "제조사",
  maker_snapshot: "제조사",
  mapping_profile: "컬럼 매핑 프로필",
  max_annual_mileage: "최대 주행거리",
  memo: "메모",
  memo_admin: "관리자메모",
  memo_agent: "영업자메모",
  memo_provider: "공급사메모",
  message: "메시지",
  mileage: "주행거리(km)",
  mileage_surcharge_snapshot: "주행거리 가산(월)",
  mileage_upcharge_per_10000km: "추가주행 금액(1만km당)",
  model: "모델명",
  model_snapshot: "모델",
  monthly_profit: "당월수익",
  name: "성명",
  net_amount: "프리패스 순수익(원)",
  options: "선택옵션",
  origin: "원산지",
  over_mileage_rate_domestic: "초과주행 국산(1km당)",
  over_mileage_rate_imported: "초과주행 수입(1km당)",
  own_damage_compensation: "[계약회사별] 자차 보상한도",
  own_damage_max_deductible: "[계약회사별] 자차 최대 면책금",
  own_damage_min_deductible: "[계약회사별] 자차 최소 면책금",
  own_damage_repair_ratio: "[계약회사별] 자차 자기부담률",
  partner: "파트너",
  partner_code: "영업(파트너)코드",
  partner_memo: "메모",
  partner_type: "유형",
  payment_due_date: "월 납부일",
  payment_method: "결제방식",
  payment_timing: "대여료 납부 조건",
  payout_rate_snapshot: "영업지급율(동결)",
  personal_driver_scope: "개인 운전범위",
  phone: "연락처",
  photo_link: "사진 링크",
  photos: "업로드 사진",
  policy: "정책",
  policy_code: "정책코드",
  policy_extra_terms: "기타사항(계약서)",
  policy_name: "정책명",
  policy_name_snapshot: "정책명",
  policy_type: "정책유형",
  price_variant_snapshot: "가격표 기준",
  product: "상품",
  product_code: "상품코드",
  product_type: "상품구분",
  product_uid: "매물UID",
  property_compensation_limit: "[계약회사별] 대물 보상한도",
  property_deductible: "[계약회사별] 대물 면책금",
  provider_agreement_done: "약정작성완료(agent)",
  provider_agreement_sent: "약정발송",
  provider_balance_confirmed: "잔금확인",
  provider_bill: "청구금액",
  provider_company_code: "공급사코드",
  provider_delivery_response: "출고응답",
  provider_docs_review: "서류확인",
  provider_incentive: "공급 인센티브",
  provider_name: "공급사명",
  provider_release_completed: "출고완료",
  provider_uid: "공급사UID",
  quote: "견적서",
  quote_code: "견적코드",
  reason: "사유",
  renewal_notice_days: "연장 사전통지기한(일)",
  rent_amount: "월대여료(원)",
  rent_amount_snapshot: "월대여료(원)",
  rent_month: "대여기간(개월)",
  rent_month_snapshot: "대여기간(개월)",
  rental_business_no: "자동차대여사업 등록번호",
  rental_region: "대여지역",
  replacement_car_policy: "대차 제공",
  report: "제보",
  report_code: "제보코드",
  reporter_name: "제보자",
  reporter_uid: "제보자 UID",
  residence_type: "거주형태",
  review_status: "심사여부(원본)",
  role: "회원 권한",
  room: "소통방",
  room_id: "방ID",
  sale_fee: "판매수수료",
  sales_notes: "특이사항(영업)",
  screening_criteria: "심사조건",
  seats: "인승",
  self_body_accident: "[계약회사별] 자손 보상한도",
  self_body_deductible: "[계약회사별] 자손 면책금",
  self_damage_exclusions: "자차 처리 제외",
  sender_code: "발신코드",
  sender_name: "발신자",
  sender_role: "발신역할",
  sender_uid: "발신UID",
  sent_at: "발송시각",
  sent_channel: "발송채널",
  settle_month: "정산월",
  settle_status: "상태",
  settlement: "정산",
  settlement_code: "정산코드",
  settlement_status: "정산상태",
  sheet_tab: "시트 gid",
  sheet_url: "구글시트 URL",
  sign_consents: "동의 항목",
  sign_draft_at: "초안 저장시각",
  sign_sent_at: "발송시각",
  sign_signature: "서명 이미지",
  sign_signed_at: "서명시각",
  sign_status: "서명 상태",
  sign_token: "서명 토큰",
  signed_pdf_url: "서명완료본",
  source_settlement_code: "원천 정산코드",
  special_terms_choice_snapshot: "특약 확인",
  special_terms_snapshot: "특약사항",
  status: "상태",
  sub_model: "세부모델",
  sub_model_snapshot: "세부모델",
  succession_allowed: "승계 가능여부",
  succession_fee: "승계수수료",
  summary: "요약",
  supplier_options: "공급사 옵션(원문)",
  supplier_vehicle_name: "공급사 차명(원문)",
  target_key: "대상키",
  text: "내용",
  transmission: "변속기",
  trim_extra_snapshot: "추가표기",
  trim_name: "세부트림",
  trim_name_snapshot: "세부트림",
  type_number: "형식번호",
  uid: "UID",
  uninsured_damage: "[계약회사별] 무보험 보상한도",
  uninsured_deductible: "[계약회사별] 무보험 면책금",
  unread_for_admin: "관리자 안읽음",
  unread_for_agent: "영업자 안읽음",
  unread_for_provider: "공급사 안읽음",
  unsigned_pdf_url: "서명요청본",
  usage: "용도",
  user: "사용자",
  user_code: "유저코드",
  valid_until: "유효기한",
  variant_snapshot: "파워트레인",
  vehicle_age_expiry_date: "차령만료일",
  vehicle_class: "차종분류",
  vehicle_name: "차량명",
  vehicle_name_snapshot: "차량명",
  vehicle_number: "차량번호",
  vehicle_price: "차량가격(원)",
  vehicle_status: "상품상태",
  view_url: "손님열람 링크",
  vin: "차대번호",
  website: "홈페이지 주소",
  year: "연식",
  year_snapshot: "연식",
};

export const 정책이름표 = (id: string): string => 정책이름[id] ?? id.replace(/_/g, ' ');

/**
 * 차종을 차종마스터 어디까지 확정했나 — ★이름표는 도메인 정본 `MATCH_LABEL` 하나를 쓴다(기능 세션 요청).
 *   「이름을 따로 짓지 말고 이걸 써 주세요 — 어느 화면이든 같은 말이어야 합니다」
 *   ⚠ 한 번 여기서 따로 지었다(「미확정」) — 도메인은 「차종 미확인」이라 같은 차가 두 말로 불릴 뻔했다.
 */
import { MATCH_LABEL } from '../../domain/product/master-match';
import type { VehicleMatchLevel } from '../../domain/product/types';
export const 매칭 = (v: VehicleMatchLevel | null | undefined): string => (v ? MATCH_LABEL[v]?.label ?? '—' : '—');
export const 매칭끝 = (v: VehicleMatchLevel | null | undefined): boolean => !!v && !!MATCH_LABEL[v]?.done;

type 정책값 =
  | { type: 'BOOLEAN'; value: boolean }
  | { type: 'NUMBER' | 'MONEY' | 'PERCENTAGE'; value: number }
  | { type: string; value: unknown };
/** 정책 값 한 칸 — 예/아니오 · 원 · % · 목록. ★모르는 값은 「—」(0 으로 꾸미지 않는다) */
export function 정책값글(p: 정책값): string {
  const v = p.value as unknown;
  if (v === null || v === undefined || v === '') return '—';
  if (p.type === 'BOOLEAN') return v ? '예' : '아니오';
  if (p.type === 'MONEY' && typeof v === 'number') return `${Math.round(v).toLocaleString('ko-KR')}원`;
  if (p.type === 'PERCENTAGE' && typeof v === 'number') return `${+(v <= 1 ? v * 100 : v).toFixed(2)}%`;
  if (typeof v === 'number') return v.toLocaleString('ko-KR');
  if (Array.isArray(v)) return v.join(', ');
  return String(v);
}
